name: tutorial-local-llm-test
channels:
  - conda-forge
dependencies:
  - _python_abi3_support=1.0.*
  - aiohappyeyeballs=2.6.*
  - aiohttp=3.13.*
  - aiosignal=1.4.*
  - airportsdata
  - annotated-doc=0.0.*
  - annotated-types=0.7.*
  - anyio=4.11.*
  - aom=3.9.*
  - appnope=0.1.*
  - argon2-cffi=25.1.*
  - argon2-cffi-bindings=25.1.*
  - arrow=1.4.*
  - astor=0.8.*
  - asttokens=3.0.*
  - async-lru=2.0.*
  - attrs=25.4.*
  - aws-c-auth=0.9.*
  - aws-c-cal=0.9.*
  - aws-c-common=0.12.*
  - aws-c-compression=0.3.*
  - aws-c-event-stream=0.5.*
  - aws-c-http=0.10.*
  - aws-c-io=0.21.*
  - aws-c-mqtt=0.13.*
  - aws-c-s3=0.8.*
  - aws-c-sdkutils=0.2.*
  - aws-checksums=0.2.*
  - aws-crt-cpp=0.32.*
  - aws-sdk-cpp=1.11.*
  - azure-core-cpp=1.14.*
  - azure-identity-cpp=1.10.*
  - azure-storage-blobs-cpp=12.13.*
  - azure-storage-common-cpp=12.8.*
  - azure-storage-files-datalake-cpp=12.12.*
  - babel=2.17.*
  - beautifulsoup4=4.14.*
  - blake3=1.0.*
  - bleach=6.3.*
  - bleach-with-css=6.3.*
  - brotli=1.1.*
  - brotli-bin=1.1.*
  - brotli-python=1.1.*
  - bzip2=1.0.*
  - c-ares=1.34.*
  - ca-certificates=2025.11.*
  - cached-property=1.5.*
  - cached_property=1.5.*
  - cachetools=6.2.*
  - cairo=1.18.*
  - cbor2=5.7.*
  - certifi=2025.11.*
  - cffi=2.0.*
  - charset-normalizer=3.4.*
  - click=8.3.*
  - cloudpickle=3.1.*
  - colorama=0.4.*
  - comm=0.2.*
  - compressed-tensors=0.9.*
  - contourpy=1.3.*
  - cpython=3.12.*
  - cycler=0.12.*
  - cyrus-sasl=2.1.*
  - dataclasses=0.8.*
  - datasets=2.2.*
  - dav1d=1.2.*
  - dbus=1.16.*
  - debugpy=1.8.*
  - decorator=5.2.*
  - defusedxml=0.7.*
  - depyf=0.18.*
  - dill=0.4.*
  - diskcache=5.6.*
  - distro=1.9.*
  - dnspython=2.8.*
  - double-conversion=3.3.*
  - einops=0.8.*
  - email-validator=2.3.*
  - email_validator=2.3.*
  - evidently=0.7.*
  - exceptiongroup=1.3.*
  - executing=2.2.*
  - fastapi=0.121.*
  - fastapi-cli=0.0.*
  - fastapi-core=0.121.*
  - ffmpeg=7.1.*
  - filelock=3.20.*
  - font-ttf-dejavu-sans-mono=2.37.*
  - font-ttf-inconsolata=3.0.*
  - font-ttf-source-code-pro
  - font-ttf-ubuntu=0.83.*
  - fontconfig=2.15.*
  - fonts-conda-ecosystem=1.*
  - fonts-conda-forge=1.*
  - fonttools=4.60.*
  - fqdn=1.5.*
  - freetype=2.14.*
  - fribidi=1.0.*
  - frozenlist=1.7.*
  - fsspec=2025.10.*
  - gdk-pixbuf=2.44.*
  - gflags=2.2.*
  - gguf=0.10.*
  - giflib=5.2.*
  - glog=0.7.*
  - glslang=16.0.*
  - gmp=6.3.*
  - gmpy2=2.2.*
  - graphite2=1.3.*
  - h11=0.16.*
  - h2=4.3.*
  - harfbuzz=12.2.*
  - hdf5=1.14.*
  - hf-xet=1.2.*
  - hpack=4.1.*
  - httpcore=1.0.*
  - httptools=0.7.*
  - httpx=0.28.*
  - huggingface_hub=0.36.*
  - hyperframe=6.1.*
  - icu=75.1.*
  - idna=3.11.*
  - imath=3.1.*
  - importlib-metadata=8.7.*
  - importlib_resources=6.5.*
  - interegular=0.3.*
  - ipykernel=7.1.*
  - ipython=9.7.*
  - ipython_pygments_lexers=1.1.*
  - ipywidgets=8.1.*
  - isoduration=20.11.*
  - jasper=4.2.*
  - jedi=0.19.*
  - jinja2=3.1.*
  - jiter=0.12.*
  - json5=0.12.*
  - jsonpointer=3.0.*
  - jsonschema=4.25.*
  - jsonschema-specifications=2025.9.*
  - jsonschema-with-format-nongpl=4.25.*
  - jupyter=1.1.*
  - jupyter-lsp=2.3.*
  - jupyter_client=8.6.*
  - jupyter_console=6.6.*
  - jupyter_core=5.9.*
  - jupyter_events=0.12.*
  - jupyter_server=2.17.*
  - jupyter_server_terminals=0.5.*
  - jupyterlab=4.5.*
  - jupyterlab_pygments=0.3.*
  - jupyterlab_server=2.28.*
  - jupyterlab_widgets=3.0.*
  - kaldi=5.5.*
  - kiwisolver=1.4.*
  - krb5=1.21.*
  - lame
  - lark=1.2.*
  - lcms2=2.17.*
  - lerc=4.0.*
  - libabseil
  - libaec=1.1.*
  - libarrow=18.1.*
  - libarrow-acero=18.1.*
  - libarrow-dataset=18.1.*
  - libarrow-substrait=18.1.*
  - libasprintf=0.25.*
  - libass=0.17.*
  - libavif16=1.3.*
  - libblas=3.11.*
  - libbrotlicommon=1.1.*
  - libbrotlidec=1.1.*
  - libbrotlienc=1.1.*
  - libcblas=3.11.*
  - libclang-cpp19.1=19.1.*
  - libclang13=21.1.*
  - libcrc32c=1.1.*
  - libcurl=8.17.*
  - libcxx=21.1.*
  - libde265=1.0.*
  - libdeflate=1.24.*
  - libedit=3.1.*
  - libev=4.33.*
  - libevent=2.1.*
  - libexpat=2.7.*
  - libffi=3.5.*
  - libfreetype=2.14.*
  - libfreetype6=2.14.*
  - libgettextpo=0.25.*
  - libgfortran=15.2.*
  - libgfortran5=15.2.*
  - libglib=2.86.*
  - libgoogle-cloud=2.36.*
  - libgoogle-cloud-storage=2.36.*
  - libgrpc=1.71.*
  - libheif=1.19.*
  - libhwloc=2.12.*
  - libhwy=1.3.*
  - libiconv=1.18.*
  - libintl=0.25.*
  - libjpeg-turbo=3.1.*
  - libjxl=0.11.*
  - liblapack=3.11.*
  - liblapacke=3.11.*
  - libllvm19=19.1.*
  - libllvm21=21.1.*
  - liblzma=5.8.*
  - libnghttp2=1.67.*
  - libntlm=1.8.*
  - libogg=1.3.*
  - libopenblas=0.3.*
  - libopencv=4.12.*
  - libopentelemetry-cpp-headers=1.21.*
  - libopenvino=2025.0.*
  - libopenvino-arm-cpu-plugin=2025.0.*
  - libopenvino-auto-batch-plugin=2025.0.*
  - libopenvino-auto-plugin=2025.0.*
  - libopenvino-hetero-plugin=2025.0.*
  - libopenvino-ir-frontend=2025.0.*
  - libopenvino-onnx-frontend=2025.0.*
  - libopenvino-paddle-frontend=2025.0.*
  - libopenvino-pytorch-frontend=2025.0.*
  - libopenvino-tensorflow-frontend=2025.0.*
  - libopenvino-tensorflow-lite-frontend=2025.0.*
  - libopus=1.5.*
  - libparquet=18.1.*
  - libpng=1.6.*
  - libpq=18.1.*
  - libprotobuf=5.29.*
  - libre2-11=2025.06.*
  - librsvg=2.58.*
  - libsentencepiece=0.2.*
  - libsodium=1.0.*
  - libsqlite=3.51.*
  - libssh2=1.11.*
  - libthrift=0.21.*
  - libtiff=4.7.*
  - libtorch=2.6.*
  - libusb=1.0.*
  - libutf8proc=2.10.*
  - libuv=1.51.*
  - libvorbis=1.3.*
  - libvpx=1.14.*
  - libvulkan-loader=1.4.*
  - libwebp-base=1.6.*
  - libxcb=1.17.*
  - libxml2=2.13.*
  - libzlib=1.3.*
  - llguidance=0.7.*
  - llvm-openmp=21.1.*
  - llvmlite=0.44.*
  - lm-format-enforcer=0.10.*
  - lz4-c=1.10.*
  - markdown-it-py=4.0.*
  - markupsafe=3.0.*
  - matplotlib=3.10.*
  - matplotlib-base=3.10.*
  - matplotlib-inline=0.2.*
  - mdurl=0.1.*
  - mistral-common=1.8.*
  - mistune=3.1.*
  - mlx=0.30.*
  - mlx-lm=0.28.*
  - mpc=1.3.*
  - mpfr=4.2.*
  - mpmath=1.3.*
  - msgspec=0.19.*
  - multidict=6.6.*
  - multiprocess=0.70.*
  - munkres=1.1.*
  - nbclient=0.10.*
  - nbconvert-core=7.16.*
  - nbformat=5.10.*
  - ncurses=6.5.*
  - nest-asyncio=1.6.*
  - networkx=3.5.*
  - ninja=1.13.*
  - nlohmann_json=3.12.*
  - nomkl=1.0.*
  - notebook=7.5.*
  - notebook-shim=0.2.*
  - numba=0.61.*
  - numpy=2.2.*
  - ollama=0.13.*
  - openai=1.90.*
  - opencv=4.12.*
  - openexr=3.3.*
  - openfst=1.8.*
  - openh264=2.6.*
  - openjpeg=2.5.*
  - openjph=0.25.*
  - openldap=2.6.*
  - openssl=3.6.*
  - optree=0.18.*
  - orc=2.1.*
  - outlines=0.1.*
  - outlines-core=0.1.*
  - overrides=7.7.*
  - packaging=25.0.*
  - pandas=2.3.*
  - pandocfilters=1.5.*
  - pango=1.56.*
  - parso=0.8.*
  - partial-json-parser=0.2.*
  - pcre2=10.46.*
  - pexpect=4.9.*
  - pillow=12.0.*
  - pip=25.3.*
  - pixman=0.46.*
  - platformdirs=4.5.*
  - prometheus-cpp=1.3.*
  - prometheus-fastapi-instrumentator=7.1.*
  - prometheus_client=0.23.*
  - prompt-toolkit=3.0.*
  - prompt_toolkit=3.0.*
  - propcache=0.3.*
  - protobuf=5.29.*
  - psutil=7.1.*
  - pthread-stubs=0.4.*
  - ptyprocess=0.7.*
  - pugixml=1.15.*
  - pure_eval=0.2.*
  - py-cpuinfo=9.0.*
  - py-opencv=4.12.*
  - pyarrow=18.1.*
  - pyarrow-core=18.1.*
  - pybase64=1.4.*
  - pybind11=3.0.*
  - pybind11-global=3.0.*
  - pycountry=24.6.*
  - pycparser=2.22.*
  - pydantic=2.12.*
  - pydantic-core=2.41.*
  - pydantic-extra-types=2.10.*
  - pygments=2.19.*
  - pyobjc-core=12.1.*
  - pyobjc-framework-cocoa=12.1.*
  - pyparsing=3.2.*
  - pysocks=1.7.*
  - python=3.12.*
  - python-dateutil=2.9.*
  - python-dotenv=1.2.*
  - python-fastjsonschema=2.21.*
  - python-gil=3.12.*
  - python-json-logger=2.0.*
  - python-multipart=0.0.*
  - python-tzdata
  - python-xxhash=3.6.*
  - python_abi=3.12.*
  - pytorch=2.6.*
  - pytz
  - pyyaml=6.0.*
  - pyzmq=27.1.*
  - qhull
  - qt6-main=6.9.*
  - rav1e=0.7.*
  - re2=2025.06.*
  - readline=8.2.*
  - referencing=0.37.*
  - regex=2025.11.*
  - requests=2.32.*
  - responses=0.18.*
  - rfc3339-validator=0.1.*
  - rfc3986-validator=0.1.*
  - rfc3987-syntax=1.1.*
  - rich=14.2.*
  - rich-toolkit=0.16.*
  - rpds-py=0.29.*
  - safetensors=0.7.*
  - scipy=1.16.*
  - sdl2=2.32.*
  - sdl3=3.2.*
  - send2trash=1.8.*
  - sentencepiece=0.2.*
  - sentencepiece-python=0.2.*
  - sentencepiece-spm=0.2.*
  - setuptools=79.0.*
  - shaderc
  - shellingham=1.5.*
  - six=1.17.*
  - sleef=3.9.*
  - snappy=1.2.*
  - sniffio=1.3.*
  - soupsieve=2.8.*
  - spirv-tools
  - stack_data=0.6.*
  - starlette=0.50.*
  - svt-av1=3.0.*
  - sympy=1.14.*
  - tbb=2022.3.*
  - terminado=0.18.*
  - tiktoken=0.12.*
  - tinycss2=1.5.*
  - tk=8.6.*
  - tokenizers=0.22.*
  - tomli=2.3.*
  - torchaudio=2.7.*
  - torchcodec=0.3.*
  - torchvision=0.21.*
  - torchvision-extra-decoders=0.0.*
  - tornado=6.5.*
  - tqdm=4.67.*
  - traitlets=5.14.*
  - transformers=4.57.*
  - typer=0.20.*
  - typer-slim=0.20.*
  - typer-slim-standard=0.20.*
  - typing-extensions=4.15.*
  - typing-inspection=0.4.*
  - typing_extensions=4.15.*
  - typing_utils=0.1.*
  - tzdata=2025b.*
  - unicodedata2=17.0.*
  - uri-template=1.3.*
  - urllib3=2.5.*
  - uvicorn=0.38.*
  - uvicorn-standard=0.38.*
  - uvloop=0.22.*
  - vllm=0.8.*
  - watchfiles=1.1.*
  - wcwidth=0.2.*
  - webcolors=25.10.*
  - webencodings=0.5.*
  - websocket-client=1.9.*
  - websockets=15.0.*
  - wheel=0.45.*
  - widgetsnbextension=4.0.*
  - x264
  - x265=3.5.*
  - xgrammar=0.1.20.*
  - xorg-libxau=1.0.*
  - xorg-libxdmcp=1.1.*
  - xxhash=0.8.*
  - yaml=0.2.*
  - yarl=1.22.*
  - zeromq=4.3.*
  - zipp=3.23.*
  - zlib=1.3.*
  - zlib-ng=2.2.*
  - zstandard=0.25.*
  - zstd=1.5.*
  - pip:
    - deepeval==3.7.*
    - lm_eval==0.4.*

prefix: "/Users/ian/miniforge3/envs/tutorial-local-llm"
